### ISSUE TITLE
add a separate dir to build the NativeAoT version

### ISSUE THREAD

**Issue by Maoni0** [Maoni0/realmon#20]
some folks have expressed the desire to use this tool without having to install .NET 6. the .net 6 requirement is just for the NativeAoT which you can always build separately. so we should not require folks to have to have 6.0. 

my suggestion is we should have a separate dir that builds AoT that does require 6.0 (instead of having everyone who wants to use this and doesn't want to install 6.0 to change `src/GCRealTimeMon/GCRealTimeMon.csproj` themselves). the rest can use 5.0 as a min version (actually we could even make it 3.1...).

**Comment by hez2010** [comment]
> the rest can use 5.0 as a min version (actually we could even make it 3.1...)

The AoT compiler works with .net 5/.net core 3.1.

**Comment by Maoni0** [comment]
then can you change it to not require 6.0? I would prefer to actually change it to 3.1.
