### ISSUE TITLE
Requires .NET 3.1.0 when newer .NET installed

### ISSUE THREAD

**Issue by accent** [Maoni0/realmon#28]
When I installed the tool and tried to run it, I get an information: required .NET 3.1.0 (runtime or SDK) while I have installed .NET 5 and 6. 

When I installed 3.1.0 SDK, it works fine.

Attaching screenshot.

![obraz](https://user-images.githubusercontent.com/700044/143755357-f1f6c194-444c-4775-b904-d6e4fc3ddd9e.png)

Expected behavior: it should run on newer version of .NET.

**Comment by Maoni0** [comment]
hi @accent! this should be fixed by ver 0.5.0 (I just verified it). could you please try and let me know if it's fixed?

**Comment by accent** [comment]
Hi @Maoni0, I confirm it's fixed.

**Comment by Maoni0** [comment]
cool! closing. fixed by [this commit](https://github.com/Maoni0/realmon/commit/9242ace03a954faa6105c26985b5967b9e5b86d2).
