### ISSUE TITLE
Session Leaks on Ctrl+C

### ISSUE THREAD

**Issue by MokoSan** [Maoni0/realmon#30]
There are instances where if the user clicks ``Ctrl+C`` to close realmon, the session isn't getting disposed. 

## Repro Steps

1. Run realmon normally and note the session name by putting a break point [here](https://github.com/Maoni0/realmon/blob/7d2bcc613dd6d46fe34342937ad186cad5508a36/src/GCRealTimeMon/Utilities/PlatformUtilities.cs#L18).
2. ``Ctrl+C`` to close the session.
3.  Open up a command line prompt / powershell in admin mode.
4.  ``logman query -ets`` to list all the sessions on the machine. Here is where I found the session still exists even after exiting the process.

Eventually, this will result in the following exception:
``Unhandled exception. System.Runtime.InteropServices.COMException (0x800705AA): Insufficient system resources exist to complete the requested service. (0x800705AA)``.

## Solution

Subscribe to the ``Console.CancelKeyPress`` event and explicitly dispose the session.

**Comment by Maoni0** [comment]
fixed by #31
